sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: nYuNLZYP5ArrHZa2FTm1c7GvYmNOSyKDSq4GKCVvYFQ3BsPXDdgKZ24J6hcDL3Mq0i3JbvWf6bj/hP/IpMD81ZaowkLciNy6/XWaPhL6gLrbrcJ6tKtAz+BN1Jsnf0b9KCLVxvIHn60JY6k9krAJH2Lvt7O+mxFVNfY9ufBKXOnJirIed0SCx9n8Ay7Yyzj8mQwtKS0EKy8XX7qrd1tJ7jvhhjPrhl9lG4kq1elC/xmafU98lY/qTygNKVPYI14U2nfwxbclDH5Do6prg43yMiSmPRa7FP1Z0vbgl5ieiviFmvCaqY1UELlIxT7a2TPsbfl/L+524IpvakC9ZLp2JO8HqJnI/B/zuURim7XeXdM5SNX3Q7IibTkMh9/GgHUcoi7LrLZFlNUeD+LPETC2bchD3HttYuVNhm4FNTOAKIk2SnKs5bbOR0dsSuk9fzP82fjNcWlF+BZmHNB0p5sEr2QhaC5b033zW677NwNX94Tc0ECG35azjbHhcrDNYq5QXwd4Iw6f8KNcOiep8JOTxzlbkIbMh4B382ez15I7K2jVXfioL4uw9tDcrZf0qd9NIPDGkxtNUqx15qCP9fGjYc8eZbag8biH59nIA30nRd9mhlgnc+MyPdVfbWiK6y3+YcLMxLdqkVWBD7vMxOeMNXf1ADRXxacgVBNMxMBXtpM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Howard-Pyle-s-Book-of-Pirates--13-Fiction-Fact--amp--Fancy-Concerning-the-Buccaneers--amp--Maro__973
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy